### ISSUE TITLE
[BUG] overflow

### ISSUE THREAD

**Issue by pzl111** [CS3219-AY2425S1/cs3219-ay2425s1-project-g05#123]
![image](https://github.com/user-attachments/assets/a6cb0578-dc1e-4343-8e73-cab275358150)

**Comment by HollaG** [comment]
Fixed in https://github.com/CS3219-AY2425S1/cs3219-ay2425s1-project-g05/commit/5a42234fc17fd1bcf4fb58d1ede225505b72f7ea
