### ISSUE TITLE
[BUG] error retrieveing history svc attempts in home page

### ISSUE THREAD

**Issue by pzl111** [CS3219-AY2425S1/cs3219-ay2425s1-project-g05#124]
![image](https://github.com/user-attachments/assets/1648d71f-5b80-441a-99d2-3f7b9763d2af)

**Comment by pzl111** [comment]
looks to be fixed

**Comment by HollaG** [comment]
This is due to nginx rate limiting due to unnecessary requests to User Service to get the name of the collaborator

**Comment by HollaG** [comment]
Fixed in https://github.com/CS3219-AY2425S1/cs3219-ay2425s1-project-g05/commit/30f31d14a161dd4a9b0e75feb7e31f2edc4a861a
