### ISSUE TITLE
[BUG] going back to delete summary

### ISSUE THREAD

**Issue by pzl111** [CS3219-AY2425S1/cs3219-ay2425s1-project-g05#125]
after deleting session summary from dashboard, go back (to go to same URL)
missing question info and solution, should not be able to come here

![image](https://github.com/user-attachments/assets/775e7920-21df-4a4a-8490-c0d307a58aaf)
![image](https://github.com/user-attachments/assets/55607fc1-ce57-4fe7-bf89-38427baa2b39)

**Comment by HollaG** [comment]
https://github.com/CS3219-AY2425S1/cs3219-ay2425s1-project-g05/commit/2013a9ed8de42478ee36c933de8cfa836e60a654
