### ISSUE TITLE
[BUG] missing test program from summary

### ISSUE THREAD

**Issue by pzl111** [CS3219-AY2425S1/cs3219-ay2425s1-project-g05#126]
after ending session, brought to summary page
test program missing data
might be due to error fetching question

![image](https://github.com/user-attachments/assets/4b285cdc-9596-499f-8022-331a59f636d3)
![image](https://github.com/user-attachments/assets/ce8bbd08-ff0a-409b-afe1-650d6f95fa24)

**Comment by HollaG** [comment]
Systemic problem, @elaineshijie need to pass in to store in the Attempt object
